// <auto-generated />
using System;
using JobApplicationAssistant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobApplicationAssistant.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422125534_AddPipelineErrorsTable")]
    partial class AddPipelineErrorsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobApplicationAssistant.Infrastructure.Persistence.Entities.JobApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_description");

                    b.Property<string>("ResumeText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resume_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("completed")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("job_applications", (string)null);
                });

            modelBuilder.Entity("JobApplicationAssistant.Infrastructure.Persistence.Entities.PipelineErrorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FailedStep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failed_step");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_application_id");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("pipeline_errors", (string)null);
                });

            modelBuilder.Entity("JobApplicationAssistant.Infrastructure.Persistence.Entities.PipelineResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cover_letter");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_application_id");

                    b.Property<string>("ResumeMatch")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resume_match");

                    b.Property<string>("ResumeRewrite")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resume_rewrite");

                    b.Property<string>("SkillExtraction")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skill_extraction");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("pipeline_results", (string)null);
                });

            modelBuilder.Entity("JobApplicationAssistant.Infrastructure.Persistence.Entities.PipelineErrorEntity", b =>
                {
                    b.HasOne("JobApplicationAssistant.Infrastructure.Persistence.Entities.JobApplicationEntity", "JobApplication")
                        .WithMany()
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("JobApplicationAssistant.Infrastructure.Persistence.Entities.PipelineResultEntity", b =>
                {
                    b.HasOne("JobApplicationAssistant.Infrastructure.Persistence.Entities.JobApplicationEntity", "JobApplication")
                        .WithMany()
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });
#pragma warning restore 612, 618
        }
    }
}
